// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://jzbcmdqnrxofxtofbedo.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6YmNtZHFucnhvZnh0b2ZiZWRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU1NzUzODgsImV4cCI6MjA5MTE1MTM4OH0.VLdjhQkXH8ZvQE1YlONCBUbXm-dVdpVOFX5R7YcM2Eo';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});
